type Post{
    id: ID!
    title: String!
    content: String!
    userAuthor: User!
}

input PostInput{
    title: String!
    content: String!
    userId: ID!
}

type Query{
    getAllPosts: [Post!]!
    getRemovedPost: [Post!]!
    getNotRemovedPost: [Post!]!
    getPost(id: ID!): Post!
}

type Mutation{
    createPost(input: PostInput!): Post!
    updatePost(id: ID!, input: PostInput!): Post!
    deletePost(id: ID!): Boolean
}
