type User {
    id: ID!
    fullname: String!
    email: String!
    active: Boolean
}

input UserInput {
    fullname: String!
    email: String!
    active: Boolean
}

type Query {
    getAllUsers: [User!]!
    getUser(id: ID!): User!
}

type Mutation {
    createUser(input: UserInput!): User!
    updateUser(id: ID!, data: UserInput!): User!
    deleteUser(id: ID!): Boolean
}

