type User {
    _id: ID!
    fullName: String!
    email: String
    active: Boolean!
}

input UserInput {
    fullName: String!
    email: String!
    active: Boolean
}

type Query {
    users: [User!]!
    getUser(id: ID!): User!
}

type Mutation {
    createUser(data: UserInput!): User!
    updateUser(id: ID!, data: UserInput!): User!
    deleteUser(id: ID!): Boolean
}

